### ISSUE TITLE
Check failed to run: 403 Forbidden ?

### ISSUE THREAD

**Issue by frederic-joventures** [sensu-plugins/sensu-plugins-graphite#14]
Hello,
I migrated to the latest version of sensu and the new version of graphite plugins.
I did not changed the check but receiving an error now : 

 /opt/sensu/embedded/bin/ruby  /opt/sensu/embedded/bin/check-graphite-data.rb -s GRAPHIT_SERVER  -t 'sensu.aws.elb.eu-west-1.flow-rotator.HTTPCode_Backend_2XX'  -w 3 -c 10

and the receive error :

Check failed to run: 403 Forbidden, ["/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:353:in `open_http'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:709:in`buffer_open'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:208:in`catch'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:149:in`open_uri'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:689:in `open'", "/opt/sensu/embedded/lib/ruby/2.0.0/open-uri.rb:34:in`open'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-graphite-0.0.7/lib/sensu-plugins-graphite/graphite_proxy/proxy.rb:87:in `retrieve_data!'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-graphite-0.0.7/bin/check-graphite-data.rb:61:in`run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in class:CLI'"]

**Comment by frederic-joventures** [comment]
I can confirm that the same check is running fine on the old server with the check-data.rb (latest version from the community plugin git repo.
both servers are using the embedded ruby

old server
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
new server
ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-linux]

**Comment by frederic-joventures** [comment]
problem was of course on my side.
