### ISSUE TITLE
How to get check to output the value from target?

### ISSUE THREAD

**Issue by jmreicha** [sensu-plugins/sensu-plugins-graphite#26]
For the `check-graphite.rb` plugin it looks like the syntax has changed for this plugin at some point in the last 6 months.  The old syntax allowed for `-c` which allows for a raw value to set as the critical threshold.

I tried the `-l / --last` option but that seems to cause the plugin to throw up.

```
Check failed to run: 757: unexpected token at '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
', ["/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "./check-graphite.rb:209:in `get_graphite_values'", "./check-graphite.rb:238:in `last_graphite_metric'", "./check-graphite.rb:437:in `check_last'", "./check-graphite.rb:488:in `block in run'", "./check-graphite.rb:479:in `each'", "./check-graphite.rb:479:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

Is there any way to grab the raw value with the new syntax?  I can get the plugin to output `Graphite OK` but that does not display any of the raw values I'm looking for.

**Comment by majormoses** [comment]
I'm guessing that the built in crit and warning thresholds are conflicting with this one:
```
$ ./bin/check-graphite.rb --help | grep -- -c
    -i, --check_function_increasing  Check that value is increasing or equal over time (use acceptable_diff_percentage if it should allow to be lower)
    -x, --complex_target             Allows complex targets which contain functions. Disables splitting on comma.
    -c, --concat_output              Include warning messages in output even if overall status is critical
```

Have you tried using `--help` and reading the options?

**Comment by majormoses** [comment]
closing due to lack of activity.
